### ISSUE TITLE
无法正常kill掉假人

### ISSUE THREAD

**Issue by ailixiyaX** [Walkersifolia/FastBotSpawn#1]
原因;报错<Elysia_mc> !!b kill
[Server] [11:31:02] [Server thread/INFO]: Can only manipulate existing players
系统环境：debian12 docker
MCDR版本：2.12.3
plugin版本：1.1.1
数据包：FZ-survival-datapack V3.1.7
minecraft版本：1.20.1fabric
mod：carpet与其各种附属 优化mod
问题：可以正常召唤假人 但是在执行kill指令时输出Can only manipulate existing players 这个输出似乎是carpet的找不到玩家？
无任何其他输出，所以无法提供
赛博神医帮帮我

**Comment by ailixiyaX** [comment]
假人前缀配置：bot_ 与地毯保持一致

**Comment by Walkersifolia** [comment]
刚刚下班看见，等我测试一下，有更多信息吗，我试着在自己服务器上复现一下

**Comment by Walkersifolia** [comment]
检查MCDR服务端的config文件夹
![image](https://github.com/Walkersifolia/FastBotSpawn/assets/129571444/52c5c31d-7d17-4787-bc93-4f10400bea40)
内的`FastBotSpawn.json`文件
![image](https://github.com/Walkersifolia/FastBotSpawn/assets/129571444/c308a5b3-8f93-4b10-a06f-dec43c93eb32)
看看里面的perfix值是否为空
![image](https://github.com/Walkersifolia/FastBotSpawn/assets/129571444/f599eebb-db06-4a98-9688-9dc1b9afdc1d)

**Comment by ailixiyaX** [comment]
![image](https://github.com/Walkersifolia/FastBotSpawn/assets/125171077/5e1e728e-a1e1-4881-bd5d-9c424934112e)

**Comment by ailixiyaX** [comment]
并不是空的

**Comment by ailixiyaX** [comment]
对比了一下自述文件上的图片发现假人名称错误，如：bot_limit1，但是今天不知道是玄学问题还是咋的自己好了？

**Comment by Walkersifolia** [comment]
> 对比了一下自述文件上的图片发现假人名称错误，如：bot_limit1，但是今天不知道是玄学问题还是咋的自己好了？

设置这个插件的前缀要带下划线阿，比如`!!b set bot_`，看你图片里估计可能是设置的时候只写了bot

**Comment by ailixiyaX** [comment]
> > 对比了一下自述文件上的图片发现假人名称错误，如：bot_limit1，但是今天不知道是玄学问题还是咋的自己好了？
> 
> 设置这个插件的前缀要带下划线阿，比如，看你图片里估计可能是设置的时候只写了bot`!!b set bot_`

其实我写了，这个是后来服内成员瞎弄的

**Comment by ailixiyaX** [comment]
![image](https://github.com/Walkersifolia/FastBotSpawn/assets/125171077/c8e9c7c6-ddd2-4347-bf95-9e2607eeba3c)
恍然大悟
![image](https://github.com/Walkersifolia/FastBotSpawn/assets/125171077/7bd807bb-7a69-4585-ac40-e64539c06aa1)
你这写错了 应该是!!b limit而不是!!b set limit 输入后者只会修改假人前缀

**Comment by Walkersifolia** [comment]
> ![image](https://private-user-images.githubusercontent.com/125171077/325981925-c8e9c7c6-ddd2-4347-bf95-9e2607eeba3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzY0MTksIm5iZiI6MTcxNDEzNjExOSwicGF0aCI6Ii8xMjUxNzEwNzcvMzI1OTgxOTI1LWM4ZTljN2M2LWRkZDItNDM0Ny1iZjk1LTllMjYwN2VlYmEzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxMjU1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWQ4ODY1NjlmNDg3ZjNlNGI0Mjc0Y2Q0MGEzZDkwY2Y3MmY5YTJmY2U1MGZmZDY4YzNiZjgxOWNlNzNjOWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tfVbTryY2YFSOoxDwFAUCIcL_Wu6c1E-QS39n-iDZlU) 恍然大悟 ![image](https://private-user-images.githubusercontent.com/125171077/325981862-7bd807bb-7a69-4585-ac40-e64539c06aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzY0MTksIm5iZiI6MTcxNDEzNjExOSwicGF0aCI6Ii8xMjUxNzEwNzcvMzI1OTgxODYyLTdiZDgwN2JiLTdhNjktNDU4NS1hYzQwLWU2NDUzOWMwNmFhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxMjU1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDM0MjNlOTJlZmYzMGNiMjNjODBjNDVkNzc3NjBmNzlmYzYyZTA5ZmFiNjMzYjhiNTM2ODI3ZTNmZjMwMGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Mso9v8ni5EZ6iLjbzmkeBeIsFajp8bNFpjUd6EXvDg) 你这写错了 应该是!!b limit而不是!!b set limit 输入后者只会修改假人前缀

![image](https://github.com/Walkersifolia/FastBotSpawn/assets/129571444/340c1a25-da93-4684-96ce-cda3ffd907f9)
确实哈，是帮助写错了，代码里我也写的是`!!b limit`，谢谢指正（

**Comment by Walkersifolia** [comment]
虽然这个更新确实很水但是还是推送一下吧（
