### ISSUE TITLE
加入批量假人动作的新功能

### ISSUE THREAD

**Issue by ailixiyaX** [Walkersifolia/FastBotSpawn#2]
如题，批量执行假人动作，目前只有丢弃物品
如：!!b action use once
虽然一般批量召唤只是用来丢东西（划掉

**Comment by Walkersifolia** [comment]
这个好写，只是当时写的时候，问服里的小伙伴觉得没多大用就没加，因为use大部分都是挂机器用嘛，基本上就是一个假人

**Comment by ailixiyaX** [comment]
em
