### ISSUE TITLE
基于bot后缀的兼容请求（

### ISSUE THREAD

**Issue by BAYUNZIYUE** [Walkersifolia/FastBotSpawn#3]
为方便tab补全快速指定特殊bot 因此bot后缀比bot前缀使用更方便 是否有兴趣支持下bot后缀设置（
基于carpet的bot_和_fake等前后缀支持）

**Comment by suoxi** [comment]
[FastBotSpawn-1.1.2.zip](https://github.com/user-attachments/files/15967583/FastBotSpawn-1.1.2.zip)

增加了"!!b suf"的指令用于添加bot后缀(zip后缀改为mcdr即可食用)

**Comment by suoxi** [comment]
[FastBotSpawn-1.1.2 .zip](https://github.com/user-attachments/files/15967691/FastBotSpawn-1.1.2.zip)
有铸币忘记改!!b clear了 故重发

**Comment by BAYUNZIYUE** [comment]
> [FastBotSpawn-1.1.2 .zip](https://github.com/user-attachments/files/15967691/FastBotSpawn-1.1.2.zip)
> 有铸币忘记改!!b clear了 故重发

\ssuoxi/

**Comment by Walkersifolia** [comment]
> [FastBotSpawn-1.1.2 .zip](https://github.com/user-attachments/files/15967691/FastBotSpawn-1.1.2.zip) 有铸币忘记改!!b clear了 故重发

谢谢佬
\suoxi/
已经更新了
