### ISSUE TITLE
希望添加点击输入

### ISSUE THREAD

**Issue by Seungmin922** [Walkersifolia/FastBotSpawn#4]
类似qb等等,点击输入就在聊天栏里

**Comment by Walkersifolia** [comment]
这个怎么说呢，我的理解是点击输入是用来简化固定的重复的复杂命令输入，例如commit之类感觉命令已经很简化了，并且不像备份或者bot list那种是较为固定的命令，也不需要commit，个人呢感觉是不需要加。不过我最近在改的perimeter maker是有点击输入，因为需要确认操作()

**Comment by Seungmin922** [comment]
ok
